name: nytimes
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  - numpy=1.26.4
  - pip
  - pip:
    - selenium==4.15.2
    - openpyxl==3.1.2
    - pandas==2.2.1
    - attrs==23.2.0
    - certifi==2024.2.2
    - cffi==1.16.0
    - charset-normalizer==3.3.2
    - cryptography==42.0.5
    - dataclasses-json==0.6.4
    - docstring_parser_fork==0.0.5
    - et-xmlfile==1.1.0
    - h11==0.14.0
    - idna==3.6
    - marshmallow==3.21.1
    - mypy-extensions==1.0.0
    - outcome==1.3.0.post0
    - packaging
    - psutil==5.9.8
    - pycparser==2.21
    - PySocks==1.7.1
    - python-dateutil==2.9.0.post0
    - python-dotenv==1.0.1
    - pytz==2024.1
    - PyYAML==6.0.1
    - robocorp==2.0.0
    - rpaframework==28.4.1
    - six==1.16.0
    - sniffio==1.3.1
    - sortedcontainers==2.4.0
    - tenacity==8.2.3
    - trio==0.25.0
    - trio-websocket==0.11.1
    - typing-inspect==0.9.0
    - typing_extensions==4.10.0
    - tzdata==2024.1
    - urllib3==2.2.1
    - webdriver-manager==4.0.1
    - wsproto==1.2.0